### ISSUE TITLE
mongoengine document methods to eve's hooks?

### ISSUE THREAD

**Issue by bhanuvrat** [seglberg/eve-mongoengine#1]
being able to define the document specific event hooks (http://python-eve.org/features.html#event-hooks) inside the document class itself would be cool.
is it possible to do that? do you have it in your todo list?

**Comment by seglberg** [comment]
Under new management!

We are going to be re-writing a significant portion of the extension. Closing issue. When the new version is released and you feel this issue still has not been resolved, please feel free to open the issue.
