### ISSUE TITLE
Projection incorrect response

### ISSUE THREAD

**Issue by mjrealm** [seglberg/eve-mongoengine#11]
When I set datasource projection to 0 and query a resource with projection 1, it doesn't return the field.

Flask
ext.add_model(User, datasource={'projection': {'image': 0}})

Explicit request:
/user?projection={"image":1} --> Should return User with "image"

http://python-eve.org/features.html#projection-filestorage

**Comment by seglberg** [comment]
Under new management!

We are going to be re-writing a significant portion of the extension. Closing issue. When the new version is released and you feel this issue still has not been resolved, please feel free to open the issue.
