### ISSUE TITLE
Pagination _meta

### ISSUE THREAD

**Issue by mjrealm** [seglberg/eve-mongoengine#12]
When requesting with "max_results" less than the total resources in DB, the _meta field returns an incorrect "total" value (it's the same as the "max_results" value).. Should be the total number of resources in DB.

**Comment by seglberg** [comment]
Under new management!

We are going to be re-writing a significant portion of the extension. Closing issue. When the new version is released and you feel this issue still has not been resolved, please feel free to open the issue.
