### ISSUE TITLE
unique constraint returns 500 instead of 409

### ISSUE THREAD

**Issue by blurrcat** [seglberg/eve-mongoengine#15]
If a field has a `unique` constraint, Eve would return 500 if a duplicate value is submitted, instead of 409.
I think this also applies to other constraints as well, since Eve only catches exceptions raised by PyMongo, not by MongoEngine.

Is there any chance that this can be fixed?

**Comment by seglberg** [comment]
Under new management!

We are going to be re-writing a significant portion of the extension. Closing issue. When the new version is released and you feel this issue still has not been resolved, please feel free to open the issue.
